version: '3'
services:
  web:
    build: .
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ../srcs/requirements/tools:/etc/nginx/ssl/
    restart: unless-stopped
